GET http://localhost:8000/transactions/range
Content-Type: application/json

{
    "type": "transactionDate",
    "lowerRange": "2023-01-01",
    "upperRange": "2023-12-31",
    "sortBy": "asc"
}
###
GET http://localhost:8000/transactions/range
Content-Type: application/json

{
    "type": "amount",
    "lowerRange": 2100,
    "upperRange": 2200,
    "sortBy": "desc"
}
###
GET http://localhost:8000/transactions
Content-Type: application/json

{
    "category": "expense",
    "sortBy": "name",
    "sortDirection": "desc"
}

###
POST http://localhost:8000/transactions
Content-Type: application/json

{
    "category": "income"
}
###
POST http://localhost:8000/transactions
Content-Type: application/json

{
    "name": "McDonalds",
    "description": "Lunch for josh",
    "category": "expense",
    "amount": 15.23,
    "transactionDate": "2023-08-22"
}
###
POST http://localhost:8000/transactions/create
Content-Type: application/json

{
    "name": "Jimmy D Realty",
    "description": "Rent for october",
    "category": "expense",
    "amount": 2100.00,
    "transactionDate": "2023-10-01"
}
###
POST http://localhost:8000/transactions/create
Content-Type: application/json

{
    "name": "State Farm Insurance",
    "description": "josh's car insurance",
    "category": "expense",
    "amount": 9999.99,
    "transactionDate": "2023-08-22"
}
###
POST http://localhost:8000/transactions
Content-Type: application/json

{
    "name": "Unit 287 Sidework",
    "description": "working with Dad",
    "category": "income",
    "amount": 105,
    "transactionDate": "2023-10-15"
}


###
GET http://localhost:8000/transactions

###
GET http://localhost:8000/transactions/month
Content-Type: application/json

{
    "month": 6
}

###
GET http://localhost:8000/transactions/date-range
Content-Type: application/json

{
    "beginDate": "March 3, 2023",
    "endDate": "July 7, 2023"
}

###
PATCH http://localhost:8000/transactions/652c16415299dafdf75f528f
Content-Type: application/json

{
    "name": "Arby's",
    "amount": 34.56,
    "transactionDate": "2022-05-23"
}

###
GET http://localhost:8000/transactions/single/64fe19d71e129a7b4f467ebd

